# Parte 1 - Escolas

In [1]:
import pandas as pd

In [5]:
url = "https://drive.google.com/uc?id=15aOJIGAyLMSY1gecjiCgu2ko_riIcKQy"

alunos = pd.read_csv(url)

In [10]:
url2 = "https://drive.google.com/uc?id=1Jgto7psHaMRTAVzcFt7D6SgJiHMB7uGT"
escolas = pd.read_csv(url2)

In [7]:
alunos

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica
0,0,Kevin Bradley,M,6,Escola A,66,79
1,1,Paul Smith,M,9,Escola A,94,61
2,2,John Rodriguez,M,9,Escola A,90,60
3,3,Oliver Scott,M,9,Escola A,67,58
4,4,William Ray,F,6,Escola A,97,84
...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98
39156,39156,Stephanie Contreras,F,8,Escola O,79,95
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94
39158,39158,Kari Holloway,F,7,Escola O,87,90
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72

In [11]:
escolas

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0           0    Escola A     Publica           2917          1910635
1           1    Escola B     Publica           2949          1884411
2           2    Escola C  Particular           1761          1056600
3           3    Escola D     Publica           4635          3022020
4           4    Escola E  Particular           1468           917500
5           5    Escola F  Particular           2283          1319574
6           6    Escola G  Particular           1858          1081356
7           7    Escola H     Publica           4976          3124928
8           8    Escola I  Particular            427           248087
9           9    Escola J  Particular            962           585858
10         10    Escola K  Particular           1800          1049400
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650
13         13    Escola N     Publica           2739          1763916
14         14    Escola O  Particular           1635          1043130

## Verificar NULL e DUPLICATED

In [12]:
alunos.isnull().sum()

ID_Estudante       0
Nome_Estudante     0
Genero             0
Serie              0
Nome_Escola        0
Nota_Redacao       0
Nota_Matematica    0
dtype: int64

In [13]:
alunos.duplicated().sum()

np.int64(0)

## Pandas merge

In [14]:
dataMerge = pd.merge(alunos, escolas)

In [15]:
dataMerge

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
0,0,Kevin Bradley,M,6,Escola A,66,79,0,Publica,2917,1910635
1,1,Paul Smith,M,9,Escola A,94,61,0,Publica,2917,1910635
2,2,John Rodriguez,M,9,Escola A,90,60,0,Publica,2917,1910635
3,3,Oliver Scott,M,9,Escola A,67,58,0,Publica,2917,1910635
4,4,William Ray,F,6,Escola A,97,84,0,Publica,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98,14,Particular,1635,1043130
39156,39156,Stephanie Contreras,F,8,Escola O,79,95,14,Particular,1635,1043130
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94,14,Particular,1635,1043130
39158,39158,Kari Holloway,F,7,Escola O,87,90,14,Particular,1635,1043130
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72,14,Particular,1635,1043130

Pergunta Importante: Qual é o dicionario de dados

## Variáveis categóricas

In [16]:
dataMerge["Serie"].unique()

array([6, 9, 8, 7])

In [17]:
dataMerge["Tipo_Escola"].unique()

<StringArray>
['Publica', 'Particular']
Length: 2, dtype: str

In [18]:
dataMerge["Nome_Escola"].unique()

<StringArray>
['Escola A', 'Escola B', 'Escola C', 'Escola D', 'Escola E', 'Escola F',
 'Escola G', 'Escola H', 'Escola I', 'Escola J', 'Escola K', 'Escola L',
 'Escola M', 'Escola N', 'Escola O']
Length: 15, dtype: str

In [19]:
dataMerge['Tipo_Escola']

0           Publica
1           Publica
2           Publica
3           Publica
4           Publica
            ...
39155    Particular
39156    Particular
39157    Particular
39158    Particular
39159    Particular
Name: Tipo_Escola, Length: 39160, dtype: str

In [20]:
dataMerge['Tipo_Escola'].unique()

<StringArray>
['Publica', 'Particular']
Length: 2, dtype: str

In [22]:
dataMerge["Tipo_Escola"].value_counts()

Tipo_Escola
Publica       26976
Particular    12184
Name: count, dtype: int64

In [25]:
dataMerge.Nome_Escola.value_counts(sort=False)

Nome_Escola
Escola A    2917
Escola B    2949
Escola C    1761
Escola D    4635
Escola E    1468
Escola F    2283
Escola G    1858
Escola H    4976
Escola I     427
Escola J     962
Escola K    1800
Escola L    3999
Escola M    4761
Escola N    2739
Escola O    1625
Name: count, dtype: int64

## Quantos alunos ficaram com nota maior que 90 em redação

Verificação cruzada dataMerge[dataMerge] => Você precisa referenciar novamente

In [29]:
dataMerge[dataMerge["Nota_Redacao"]==77]

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
47,47,Ellen Brown,F,8,Escola A,77,81,0,Publica,2917,1910635
63,63,Ronnie Conley,M,8,Escola A,77,61,0,Publica,2917,1910635
66,66,Dylan Taylor MD,M,7,Escola A,77,93,0,Publica,2917,1910635
84,84,Joseph Butler,M,7,Escola A,77,63,0,Publica,2917,1910635
96,96,Jessica Smith,F,6,Escola A,77,72,0,Publica,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39050,39050,Michael Reed,M,9,Escola O,77,70,14,Particular,1635,1043130
39051,39051,Matthew Ball,M,8,Escola O,77,97,14,Particular,1635,1043130
39072,39072,Amanda Ramirez,F,9,Escola O,77,73,14,Particular,1635,1043130
39133,39133,Emily Gomez,F,9,Escola O,77,93,14,Particular,1635,1043130
39144,39144,Cristian Webster,M,9,Escola O,77,87,14,Particular,1635,1043130

### Função filtrar nota

In [65]:
def grade_filter(subject, grade):
    print("A disciplina escolhida, foi:", subject)
    print("A nota escolhida", grade)
    print("Número de alunos: ", len(dataMerge[dataMerge[subject]>=grade]))
    return dataMerge[dataMerge[subject]>=grade]

In [66]:
grade_filter("Nota_Redacao", 77)

A disciplina escolhida, foi: Nota_Redacao
A nota escolhida 77
Número de alunos:  25845

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
1,1,Paul Smith,M,9,Escola A,94,61,0,Publica,2917,1910635
2,2,John Rodriguez,M,9,Escola A,90,60,0,Publica,2917,1910635
4,4,William Ray,F,6,Escola A,97,84,0,Publica,2917,1910635
5,5,James Miranda,M,6,Escola A,94,94,0,Publica,2917,1910635
6,6,Benjamin Carter,F,8,Escola A,82,80,0,Publica,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98,14,Particular,1635,1043130
39156,39156,Stephanie Contreras,F,8,Escola O,79,95,14,Particular,1635,1043130
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94,14,Particular,1635,1043130
39158,39158,Kari Holloway,F,7,Escola O,87,90,14,Particular,1635,1043130
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72,14,Particular,1635,1043130

In [ ]:
def grade_filter_percent(subject: str, grade: int):
    print("A disciplina escolhida, foi:", subject)
    print("A nota escolhida", grade)
    print("Número de alunos: ", len(dataMerge[dataMerge[subject]>=grade]))
    return len(dataMerge[dataMerge[subject]>grade]/len(alunos)*100)

In [76]:
grade_filter_percent("Nota_Redacao", 95)

A disciplina escolhida, foi: Nota_Redacao
A nota escolhida 95
Número de alunos:  5477

TypeError: unsupported operand type(s) for /: 'str' and 'int'