In [1]:
url = "https://servicodados.ibge.gov.br/api/v3/agregados/4093/periodos/201201|201202|201203|201204|201301|201302|201303|201304|201401|201402|201403|201404|201501|201502|201503|201504|201601|201602|201603|201604|201701|201702|201703|201704|201801|201802|201803|201804|201901|201902|201903|201904|202001|202002|202003|202004|202101|202102|202103|202104|202201|202202|202203|202204|202301|202302|202303|202304|202401|202402|202403|202404|202501|202502|202503|202504/variaveis/4099?localidades=N3[26]&classificacao=2[6794]"

In [2]:
import pandas as pd
data = pd.read_json(url)

In [3]:
serie = data['resultados'][0][0]['series'][0]['serie']

In [4]:
df = pd.DataFrame.from_dict(serie, orient='index', columns=['valor'])
df.index.name = 'periodo'
df = df.reset_index()

In [5]:
df.head()

  periodo valor
0  201201   9.6
1  201202   8.3
2  201203   9.4
3  201204   9.2
4  201301  10.7

In [6]:
df = df.replace('...', '0')

### Transformar [valor em FLOAT]

In [7]:
df['valor'] = df['valor'].astype('float')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   periodo  56 non-null     str
 1   valor    56 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.0 KB

In [10]:
df.head()

  periodo  valor
0  201201    9.6
1  201202    8.3
2  201203    9.4
3  201204    9.2
4  201301   10.7

### Periodo tem que virar data

In [28]:
df['ano'] = df['periodo'].str[:4].astype('int')

In [29]:
df['trimestre'] = df['periodo'].str[-2:].astype('int')

In [32]:
df

   periodo  valor   ano  trimestre
0   201201    9.6  2012          1
1   201202    8.3  2012          2
2   201203    9.4  2012          3
3   201204    9.2  2012          4
4   201301   10.7  2013          1
5   201302    9.7  2013          2
6   201303    8.5  2013          3
7   201304    7.4  2013          4
8   201401    8.8  2014          1
9   201402    8.0  2014          2
10  201403    8.5  2014          3
11  201404    7.7  2014          4
12  201501    8.2  2015          1
13  201502    9.2  2015          2
14  201503   11.3  2015          3
15  201504   11.1  2015          4
16  201601   13.4  2016          1
17  201602   14.2  2016          2
18  201603   15.5  2016          3
19  201604   15.9  2016          4
20  201701   17.3  2017          1
21  201702   19.0  2017          2
22  201703   18.1  2017          3
23  201704   17.0  2017          4
24  201801   17.9  2018          1
25  201802   17.1  2018          2
26  201803   17.0  2018          3
27  201804   15.6  2018          4
28  201901   16.3  2019          1
29  201902   16.1  2019          2
30  201903   16.0  2019          3
31  201904   14.2  2019          4
32  202001   14.8  2020          1
33  202002    0.0  2020          2
34  202003    0.0  2020          3
35  202004    0.0  2020          4
36  202101    0.0  2021          1
37  202102    0.0  2021          2
38  202103    0.0  2021          3
39  202104    0.0  2021          4
40  202201    0.0  2022          1
41  202202   13.6  2022          2
42  202203   14.0  2022          3
43  202204   12.3  2022          4
44  202301   14.1  2023          1
45  202302   14.2  2023          2
46  202303   13.3  2023          3
47  202304   12.0  2023          4
48  202401   12.4  2024          1
49  202402   11.6  2024          2
50  202403   10.6  2024          3
51  202404   10.3  2024          4
52  202501   11.6  2025          1
53  202502   10.4  2025          2
54  202503   10.0  2025          3
55  202504    8.8  2025          4

In [36]:
df['periodo'] = pd.PeriodIndex(df['ano'].astype('str') + 'Q' + df['trimestre'].astype('str'), freq='Q')

In [37]:
df

   periodo  valor   ano  trimestre
0   2012Q1    9.6  2012          1
1   2012Q2    8.3  2012          2
2   2012Q3    9.4  2012          3
3   2012Q4    9.2  2012          4
4   2013Q1   10.7  2013          1
5   2013Q2    9.7  2013          2
6   2013Q3    8.5  2013          3
7   2013Q4    7.4  2013          4
8   2014Q1    8.8  2014          1
9   2014Q2    8.0  2014          2
10  2014Q3    8.5  2014          3
11  2014Q4    7.7  2014          4
12  2015Q1    8.2  2015          1
13  2015Q2    9.2  2015          2
14  2015Q3   11.3  2015          3
15  2015Q4   11.1  2015          4
16  2016Q1   13.4  2016          1
17  2016Q2   14.2  2016          2
18  2016Q3   15.5  2016          3
19  2016Q4   15.9  2016          4
20  2017Q1   17.3  2017          1
21  2017Q2   19.0  2017          2
22  2017Q3   18.1  2017          3
23  2017Q4   17.0  2017          4
24  2018Q1   17.9  2018          1
25  2018Q2   17.1  2018          2
26  2018Q3   17.0  2018          3
27  2018Q4   15.6  2018          4
28  2019Q1   16.3  2019          1
29  2019Q2   16.1  2019          2
30  2019Q3   16.0  2019          3
31  2019Q4   14.2  2019          4
32  2020Q1   14.8  2020          1
33  2020Q2    0.0  2020          2
34  2020Q3    0.0  2020          3
35  2020Q4    0.0  2020          4
36  2021Q1    0.0  2021          1
37  2021Q2    0.0  2021          2
38  2021Q3    0.0  2021          3
39  2021Q4    0.0  2021          4
40  2022Q1    0.0  2022          1
41  2022Q2   13.6  2022          2
42  2022Q3   14.0  2022          3
43  2022Q4   12.3  2022          4
44  2023Q1   14.1  2023          1
45  2023Q2   14.2  2023          2
46  2023Q3   13.3  2023          3
47  2023Q4   12.0  2023          4
48  2024Q1   12.4  2024          1
49  2024Q2   11.6  2024          2
50  2024Q3   10.6  2024          3
51  2024Q4   10.3  2024          4
52  2025Q1   11.6  2025          1
53  2025Q2   10.4  2025          2
54  2025Q3   10.0  2025          3
55  2025Q4    8.8  2025          4

In [38]:
df['periodo'] = df['periodo'].dt.to_timestamp()

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   periodo    56 non-null     datetime64[us]
 1   valor      56 non-null     float64
 2   ano        56 non-null     int64
 3   trimestre  56 non-null     int64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 1.9 KB