Pandas

In [1]:
import pandas as pd

In [7]:
url = "https://drive.google.com/uc?id=1Jgto7psHaMRTAVzcFt7D6SgJiHMB7uGT"

escolas = pd.read_csv(url)

In [9]:
type(escolas)

pandas.DataFrame

In [10]:
escolas.describe()

       ID_Escola  Numero_Alunos  Orcamento_Anual
count  15.000000      15.000000     1.500000e+01
mean    7.000000    2611.333333     1.643295e+06
std     4.472136    1420.915282     9.347763e+05
min     0.000000     427.000000     2.480870e+05
25%     3.500000    1698.000000     1.046265e+06
50%     7.000000    2283.000000     1.319574e+06
75%    10.500000    3474.000000     2.228999e+06
max    14.000000    4976.000000     3.124928e+06

In [11]:
escolas

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0           0    Escola A     Publica           2917          1910635
1           1    Escola B     Publica           2949          1884411
2           2    Escola C  Particular           1761          1056600
3           3    Escola D     Publica           4635          3022020
4           4    Escola E  Particular           1468           917500
5           5    Escola F  Particular           2283          1319574
6           6    Escola G  Particular           1858          1081356
7           7    Escola H     Publica           4976          3124928
8           8    Escola I  Particular            427           248087
9           9    Escola J  Particular            962           585858
10         10    Escola K  Particular           1800          1049400
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650
13         13    Escola N     Publica           2739          1763916
14         14    Escola O  Particular           1635          1043130

Média

In [15]:
escolas['Numero_Alunos'].mean()

np.float64(2611.3333333333335)

In [16]:
escolas.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Escola        15 non-null     int64
 1   Nome_Escola      15 non-null     str
 2   Tipo_Escola      15 non-null     str
 3   Numero_Alunos    15 non-null     int64
 4   Orcamento_Anual  15 non-null     int64
dtypes: int64(3), str(2)
memory usage: 732.0 bytes

Validação de dados faltantes

In [17]:
escolas.isnull().sum()

ID_Escola          0
Nome_Escola        0
Tipo_Escola        0
Numero_Alunos      0
Orcamento_Anual    0
dtype: int64

In [18]:
escolas.isnull()

    ID_Escola  Nome_Escola  Tipo_Escola  Numero_Alunos  Orcamento_Anual
0       False        False        False          False            False
1       False        False        False          False            False
2       False        False        False          False            False
3       False        False        False          False            False
4       False        False        False          False            False
5       False        False        False          False            False
6       False        False        False          False            False
7       False        False        False          False            False
8       False        False        False          False            False
9       False        False        False          False            False
10      False        False        False          False            False
11      False        False        False          False            False
12      False        False        False          False            False
13      False        False        False          False            False
14      False        False        False          False            False

Verificação Not A Number

In [19]:
escolas.isna().sum()

ID_Escola          0
Nome_Escola        0
Tipo_Escola        0
Numero_Alunos      0
Orcamento_Anual    0
dtype: int64

Verificação de dados duplicados

In [20]:
escolas.duplicated().sum()

np.int64(0)

Descrição dos dados

In [21]:
escolas.describe()

       ID_Escola  Numero_Alunos  Orcamento_Anual
count  15.000000      15.000000     1.500000e+01
mean    7.000000    2611.333333     1.643295e+06
std     4.472136    1420.915282     9.347763e+05
min     0.000000     427.000000     2.480870e+05
25%     3.500000    1698.000000     1.046265e+06
50%     7.000000    2283.000000     1.319574e+06
75%    10.500000    3474.000000     2.228999e+06
max    14.000000    4976.000000     3.124928e+06

In [25]:
escolas[escolas["Numero_Alunos"] > 3000]

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
3           3    Escola D     Publica           4635          3022020
7           7    Escola H     Publica           4976          3124928
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650