In [3]:
url = "https://servicodados.ibge.gov.br/api/v3/agregados/4093/periodos/201201|201202|201203|201204|201301|201302|201303|201304|201401|201402|201403|201404|201501|201502|201503|201504|201601|201602|201603|201604|201701|201702|201703|201704|201801|201802|201803|201804|201901|201902|201903|201904|202001|202002|202003|202004|202101|202102|202103|202104|202201|202202|202203|202204|202301|202302|202303|202304|202401|202402|202403|202404|202501|202502|202503|202504/variaveis/4099?localidades=N3[26]&classificacao=2[6794]"

In [4]:
import pandas as pd
data = pd.read_json(url)

In [5]:
serie = data['resultados'][0][0]['series'][0]['serie']

In [6]:
df = pd.DataFrame.from_dict(serie, orient='index', columns=['valor'])
df.index.name = 'periodo'
df = df.reset_index()

In [7]:
df.head()

  periodo valor
0  201201   9.6
1  201202   8.3
2  201203   9.4
3  201204   9.2
4  201301  10.7

In [8]:
df = df.replace('...', '0')

### Transformar [valor em FLOAT]

In [9]:
df['valor'] = df['valor'].astype('float')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   periodo  56 non-null     str
 1   valor    56 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.0 KB

In [11]:
df.head()

  periodo  valor
0  201201    9.6
1  201202    8.3
2  201203    9.4
3  201204    9.2
4  201301   10.7

### Periodo tem que virar data

In [12]:
df['ano'] = df['periodo'].str[:4].astype('int')

In [13]:
df['trimestre'] = df['periodo'].str[-2:].astype('int')

In [15]:
df['periodo'] = pd.PeriodIndex(df['ano'].astype('str') + 'Q' + df['trimestre'].astype('str'), freq='Q')

In [17]:
df['periodo'] = df['periodo'].dt.to_timestamp()

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   periodo    56 non-null     datetime64[us]
 1   valor      56 non-null     float64
 2   ano        56 non-null     int64
 3   trimestre  56 non-null     int64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 1.9 KB